let movies = [
    {
        titulo: "Blade Runner",
        ano: 1982,
        genero: "Ficção Científica",
        descricao: "No ano de 2019, a Terra está sobrecarregada, com humanos vivendo em um mundo decadente e poluído. Andróides chamados replicantes são criados para trabalhos perigosos nas colônias fora do planeta. Deckard, um Blade Runner, é encarregado de caçá-los e eliminá-los, mas começa a questionar sua própria humanidade.",
        diretor: "Ridley Scott",
        elenco: "Harrison Ford, Rutger Hauer, Sean Young",
        link: "https://www.imdb.com/title/tt0083658/",
        poster: "https://m.media-amazon.com/images/M/MV5BMWMwZjZjZjctMjI1ZC00MTRlLWE1MzktMDZjZDI1MjU2OTQxXkEyXkFqcGc@._V1_.jpg",
    },
    {
        titulo: "Mad Max",
        ano: 1979,
        genero: "Ação/Pós-apocalíptico",
        descricao: "Em um futuro pós-apocalíptico na Austrália, as estradas são dominadas por gangues violentas e recursos como gasolina são escassos. Max Rockatansky, um ex-policial, busca vingança contra uma gangue que matou sua família.",
        diretor: "George Miller",
        elenco: "Mel Gibson, Joanne Samuel, Hugh Keays-Byrne",
        link: "https://www.imdb.com/title/tt0079501/",
        poster: "https://m.media-amazon.com/images/M/MV5BNTBkODc3OTAtMTFkZi00ZmNlLWI5ODktY2M3NDJhMDY5ZDA0XkEyXkFqcGdeQXVyMTY4MjE1MDA@._V1_.jpg",
    },
    {
        titulo: "Alien: O Oitavo Passageiro",
        ano: 1979,
        genero: "Terror/Ficção Científica",
        descricao: "Em um futuro distante, a tripulação da nave Nostromo recebe um sinal de socorro de um planeta deserto e encontra uma forma de vida alienígena mortal.",
        diretor: "Ridley Scott",
        elenco: "Sigourney Weaver, Tom Skerritt, John Hurt",
        link: "https://www.imdb.com/title/tt0078748/",
        poster: "https://m.media-amazon.com/images/M/MV5BOGQzZTBjMjQtOTVmMS00NGE5LWEyYmMtOGQ1ZGZjNmRkYjFhXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
    },
    {
        titulo: "Fuga no Século 23 (Logan's Run)",
        ano: 1976,
        genero: "Ficção Científica",
        descricao: "No ano de 2274, a humanidade vive em uma sociedade utópica, mas todos são exterminados aos 30 anos. Logan 5, um agente, tenta escapar quando sua vez chega.",
        diretor: "Michael Anderson",
        elenco: "Michael York, Jenny Agutter, Richard Jordan",
        link: "https://www.imdb.com/title/tt0074812/",
        poster: "https://m.media-amazon.com/images/M/MV5BNWFmOGQ3NmItY2QzZC00ODdlLWE2NjMtM2I5YTdjYjk4YjUwXkEyXkFqcGc@._V1_.jpg",
    },
    {
        titulo: "THX 1138",
        ano: 1971,
        genero: "Ficção Científica/Distopia",
        descricao: "Em uma sociedade distópica do futuro, onde as emoções são controladas por drogas e o governo monitora rigorosamente cada aspecto da vida dos cidadãos, THX 1138 começa a questionar o sistema.",
        diretor: "George Lucas",
        elenco: "Robert Duvall, Donald Pleasence, Don Pedro Colley",
        link: "https://www.imdb.com/title/tt0066434/",
        poster: "https://m.media-amazon.com/images/M/MV5BZDI3MDRjMzMtMDA1ZS00NDdmLWEwZWUtYzJmMzQyYmIxN2E4XkEyXkFqcGdeQXVyMTUzMDUzNTI3._V1_.jpg",
    },
    {
        titulo: "De Volta para o Futuro",
        ano: 1985,
        genero: "Aventura/Ficção Científica",
        descricao: "Marty McFly, um adolescente comum, é acidentalmente enviado 30 anos para o passado em um carro DeLorean viajante no tempo inventado pelo excêntrico cientista Doc Brown.",
        diretor: "Robert Zemeckis",
        elenco: "Michael J. Fox, Christopher Lloyd, Lea Thompson",
        link: "https://www.imdb.com/title/tt0088763/",
        poster: "https://m.media-amazon.com/images/M/MV5BZDcyNmYxN2QtMmViZS00NTQ4LTlhZTAtZjc4MzY2Yjg0M2ZmXkEyXkFqcGc@._V1_.jpg",
    },
    {
        titulo: "O Exterminador do Futuro",
        ano: 1984,
        genero: "Ação/Ficção Científica",
        descricao: "Um ciborgue assassino é enviado de volta no tempo para matar Sarah Connor, cujo filho ainda não nascido se tornará o salvador da humanidade.",
        diretor: "James Cameron",
        elenco: "Arnold Schwarzenegger, Linda Hamilton, Michael Biehn",
        link: "https://www.imdb.com/title/tt0088247/",
        poster: "https://m.media-amazon.com/images/M/MV5BYzhhM2Y3NzctZmExNy00NjRlLThiYWEtZmEwYjU3MWUwNDM3XkEyXkFqcGc@._V1_.jpg",
    },
    {
        titulo: "Star Wars: Uma Nova Esperança",
        ano: 1977,
        genero: "Ficção Científica/Aventura",
        descricao: "Luke Skywalker une forças com um cavaleiro Jedi, um mercenário, um wookiee e dois dróides para salvar a galáxia e a princesa Leia do terrível Darth Vader.",
        diretor: "George Lucas",
        elenco: "Mark Hamill, Harrison Ford, Carrie Fisher",
        link: "https://www.imdb.com/title/tt0076759/",
        poster: "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_.jpg",
    },
    {
        titulo: "O Iluminado",
        ano: 1980,
        genero: "Terror/Suspense",
        descricao: "Um escritor e sua família ficam isolados em um hotel remoto durante o inverno, onde o escritor começa a enlouquecer devido à presença maligna do hotel.",
        diretor: "Stanley Kubrick",
        elenco: "Jack Nicholson, Shelley Duvall, Danny Lloyd",
        link: "https://www.imdb.com/title/tt0081505/",
        poster: "https://m.media-amazon.com/images/M/MV5BYmUxZDU3NjktMzA1OS00OGUwLWJkOTctYzhjOGI5MTcyY2U3XkEyXkFqcGc@._V1_.jpg",
    },
    {
        titulo: "A Hora do Pesadelo",
        ano: 1984,
        genero: "Terror",
        descricao: "Freddy Krueger, um assassino com luvas de lâminas, ataca adolescentes em seus sonhos, o que resulta em suas mortes na vida real.",
        diretor: "Wes Craven",
        elenco: "Heather Langenkamp, Robert Englund, Johnny Depp",
        link: "https://www.imdb.com/title/tt0087800/",
        poster: "https://m.media-amazon.com/images/M/MV5BNzFjZmM1ODgtMDBkMS00NWFlLTg2YmUtZjc3ZTgxMjE1OTI2L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg",
    },
    {
        titulo: "Poltergeist: O Fenômeno",
        ano: 1982,
        genero: "Terror",
        descricao: "Uma família suburbana é assombrada por fantasmas que sequestram sua filha, forçando-os a enfrentar uma série de eventos sobrenaturais.",
        diretor: "Tobe Hooper",
        elenco: "JoBeth Williams, Heather O'Rourke, Craig T. Nelson",
        link: "https://www.imdb.com/title/tt0084516/",
        poster: "https://m.media-amazon.com/images/M/MV5BYTJkYzAxNjgtMTY5NC00MjQzLWI5OTgtZmI2NzhjNzdhMDFkXkEyXkFqcGdeQXVyMTY4MjE1MDA@._V1_.jpg",
    },
    {
        titulo: "Indiana Jones e os Caçadores da Arca Perdida",
        ano: 1981,
        genero: "Aventura",
        descricao: "O arqueólogo Indiana Jones enfrenta os nazistas para encontrar a Arca da Aliança, que detém um poder místico.",
        diretor: "Steven Spielberg",
        elenco: "Harrison Ford, Karen Allen, Paul Freeman",
        link: "https://www.imdb.com/title/tt0082971/",
        poster: "https://m.media-amazon.com/images/M/MV5BZWE3OGQwYWMtNjAxMi00YjI4LWI3OWUtZjhkZTgxYjdkZDA4XkEyXkFqcGdeQXVyNzg5MzIyOA@@._V1_.jpg",
    },
    {
        titulo: "Rocky: Um Lutador",
        ano: 1976,
        genero: "Drama/Esporte",
        descricao: "Um boxeador desconhecido da Filadélfia, Rocky Balboa, ganha uma chance de lutar pelo título mundial de pesos pesados.",
        diretor: "John G. Avildsen",
        elenco: "Sylvester Stallone, Talia Shire, Burt Young",
        link: "https://www.imdb.com/title/tt0075148/",
        poster: "https://m.media-amazon.com/images/M/MV5BZGJhOTdkZWMtNmIyYi00NDY4LThiODUtNWIxNTIyYmNhN2FmXkEyXkFqcGdeQXVyMTAyOTE2ODg0._V1_.jpg",
    },
    {
        titulo: "Taxi Driver",
        ano: 1976,
        genero: "Drama/Crime",
        descricao: "Travis Bickle, um ex-combatente do Vietnã e taxista de Nova York, se torna cada vez mais desconectado da realidade e começa a planejar um ataque violento.",
        diretor: "Martin Scorsese",
        elenco: "Robert De Niro, Jodie Foster, Cybill Shepherd",
        link: "https://www.imdb.com/title/tt0075314/",
        poster: "https://m.media-amazon.com/images/M/MV5BMTI2YjhiZDktNGJhOS00M2M3LWJiMGEtOWQ5ZDc5MjIwODhiXkEyXkFqcGc@._V1_.jpg",
    },
    {
        titulo: "Guerra nas Estrelas: O Império Contra-Ataca",
        ano: 1980,
        genero: "Ficção Científica/Aventura",
        descricao: "Após a destruição da Estrela da Morte, a Aliança Rebelde enfrenta o ataque implacável das forças do Império lideradas por Darth Vader.",
        diretor: "Irvin Kershner",
        elenco: "Mark Hamill, Harrison Ford, Carrie Fisher",
        link: "https://www.imdb.com/title/tt0080684/",
        poster: "https://m.media-amazon.com/images/M/MV5BY2ViMjFhMDMtNTA4Yi00NGJjLTk0ZTktNGVkZjJjMGY4ZTFkXkEyXkFqcGc@._V1_.jpg",
    },
    {
        titulo: "E.T.: O Extraterrestre",
        ano: 1982,
        genero: "Família/Ficção Científica",
        descricao: "Um garoto faz amizade com um alienígena que ficou preso na Terra e tenta ajudá-lo a voltar para casa enquanto mantém a amizade em segredo do governo.",
        diretor: "Steven Spielberg",
        elenco: "Henry Thomas, Drew Barrymore, Dee Wallace",
        link: "https://www.imdb.com/title/tt0083866/",
        poster: "https://m.media-amazon.com/images/M/MV5BMDcxNzNiNmYtNzZmZi00ZjYxLTljOWMtMWJhYTZmM2E0ZTlhXkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg",
    },
    {
        titulo: "Os Caça-Fantasmas",
        ano: 1984,
        genero: "Comédia/Fantasia",
        descricao: "Um grupo de cientistas que perde seu financiamento acadêmico decide abrir um negócio de caça-fantasmas, mas enfrenta uma ameaça sobrenatural que pode destruir a cidade.",
        diretor: "Ivan Reitman",
        elenco: "Bill Murray, Dan Aykroyd, Sigourney Weaver",
        link: "https://www.imdb.com/title/tt0087332/",
        poster: "https://cdn.panrotas.com.br/portal-panrotas-statics/media-files-cache/279299/2496d753eb216aa26831ec29dd6d0942unnamed1/46,0,500,750/400,600,0.39/0/default.jpg",
    },
    {
        titulo: "O Enigma de Outro Mundo",
        ano: 1982,
        genero: "Terror/Ficção Científica",
        descricao: "Uma equipe de cientistas na Antártida enfrenta uma forma de vida alienígena que pode imitar qualquer ser vivo que consome, levando a uma paranoia mortal.",
        diretor: "John Carpenter",
        elenco: "Kurt Russell, Wilford Brimley, Keith David",
        link: "https://www.imdb.com/title/tt0084787/",
        poster: "https://m.media-amazon.com/images/M/MV5BNTliMTUwYWEtYWEyMS00OGY5LTk5MDQtZmNmNWUzZTc3M2RlXkEyXkFqcGdeQXVyMTAyOTE2ODg0._V1_.jpg",
    },
    {
        titulo: "Scarface",
        ano: 1983,
        genero: "Crime/Drama",
        descricao: "Tony Montana, um imigrante cubano, luta para subir no mundo do crime em Miami, mas sua ambição ilimitada leva à sua eventual queda.",
        diretor: "Brian De Palma",
        elenco: "Al Pacino, Michelle Pfeiffer, Steven Bauer",
        link: "https://www.imdb.com/title/tt0086250/",
        poster: "https://m.media-amazon.com/images/M/MV5BZGIxMGI0YmItZGJkMi00MmY1LWE4YWYtMmU2OWRhODEwZTg1XkEyXkFqcGc@._V1_.jpg",
    },
    {
        titulo: "Clube dos Cinco",
        ano: 1985,
        genero: "Drama/Comédia",
        descricao: "Cinco adolescentes de diferentes círculos sociais são obrigados a passar um sábado juntos em detenção e acabam descobrindo que têm mais em comum do que imaginavam.",
        diretor: "John Hughes",
        elenco: "Molly Ringwald, Emilio Estevez, Judd Nelson",
        link: "https://www.imdb.com/title/tt0088847/",
        poster: "https://m.media-amazon.com/images/M/MV5BYjMyYzFlYjMtYjVmOC00MDUzLWJiZTAtNDE1M2EzNzhhZjM5XkEyXkFqcGc@._V1_.jpg",
    },
    {
        titulo: "Amadeus",
        ano: 1984,
        genero: "Drama/Biografia",
        descricao: "A vida de Wolfgang Amadeus Mozart contada do ponto de vista de seu rival ciumento, Antonio Salieri, que planeja sua queda.",
        diretor: "Milos Forman",
        elenco: "F. Murray Abraham, Tom Hulce, Elizabeth Berridge",
        link: "https://www.imdb.com/title/tt0086879/",
        poster: "https://m.media-amazon.com/images/M/MV5BNzI2MjM5NDEtNjJmZS00NTJiLTlkY2UtYjJhOGViYmU2ZTIxXkEyXkFqcGdeQXVyMTU3NTI2OTky._V1_.jpg",
    },
    {
        titulo: "Halloween: A Noite do Terror",
        ano: 1978,
        genero: "Terror",
        descricao: "Michael Myers, um assassino em série que fugiu de um hospital psiquiátrico, retorna à sua cidade natal para causar mais terror na noite de Halloween.",
        diretor: "John Carpenter",
        elenco: "Donald Pleasence, Jamie Lee Curtis, Tony Moran",
        link: "https://www.imdb.com/title/tt0077651/",
        poster: "https://m.media-amazon.com/images/M/MV5BOGIzYTBjYTAtNDEyYi00MjUxLWIyMzgtNjk3YTkzMTViMmUwXkEyXkFqcGdeQXVyMjE4ODEzMjg@._V1_.jpg",
    },
    {
        titulo: "Apocalypse Now",
        ano: 1979,
        genero: "Drama/Guerra",
        descricao: "Durante a Guerra do Vietnã, o Capitão Willard é enviado em uma perigosa missão para assassinar o Coronel Kurtz, que enlouqueceu e comanda uma força de guerreiros locais.",
        diretor: "Francis Ford Coppola",
        elenco: "Martin Sheen, Marlon Brando, Robert Duvall",
        link: "https://www.imdb.com/title/tt0078788/",
        poster: "",
    },
    {
        titulo: "Karatê Kid: A Hora da Verdade",
        ano: 1984,
        genero: "Drama/Esporte",
        descricao: "Um jovem aprende karatê com um mestre japonês para se defender de valentões e ganhar um torneio importante.",
        diretor: "John G. Avildsen",
        elenco: "Ralph Macchio, Pat Morita, Elisabeth Shue",
        link: "https://www.imdb.com/title/tt0087538/",
        poster: "https://m.media-amazon.com/images/M/MV5BYmQyNTA1ZGItNjZjMi00NzFlLWEzMWEtNWMwN2Q2MjJhYzEyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
    },
    {
        titulo: "Platoon",
        ano: 1986,
        genero: "Drama/Guerra",
        descricao: "Um jovem recruta no Vietnã enfrenta os horrores da guerra e as tensões dentro de seu próprio pelotão enquanto tenta manter sua humanidade intacta.",
        diretor: "Oliver Stone",
        elenco: "Charlie Sheen, Tom Berenger, Willem Dafoe",
        link: "https://www.imdb.com/title/tt0091763/",
        poster: "https://m.media-amazon.com/images/M/MV5BMzRjZjdlMjQtODVkYS00N2YzLWJlYWYtMGVlN2E5MWEwMWQzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
    },
    {
        titulo: "Top Gun: Ases Indomáveis",
        ano: 1986,
        genero: "Ação/Drama",
        descricao: "Um jovem piloto talentoso é aceito na escola de elite Top Gun, onde deve competir com outros pilotos e lidar com seu próprio ego.",
        diretor: "Tony Scott",
        elenco: "Tom Cruise, Kelly McGillis, Val Kilmer",
        link: "https://www.imdb.com/title/tt0092099/",
        poster: "https://m.media-amazon.com/images/M/MV5BMDUzNTIzZTAtYzEwOC00MmUwLWI1MjgtMzkwODhiMThhYzk3XkEyXkFqcGc@._V1_.jpg",
    },
    {
        titulo: "Labirinto: A Magia do Tempo",
        ano: 1986,
        genero: "Fantasia",
        descricao: "Uma jovem deve navegar por um labirinto mágico para resgatar seu irmão sequestrado pelo Rei dos Duendes.",
        diretor: "Jim Henson",
        elenco: "David Bowie, Jennifer Connelly, Toby Froud",
        link: "https://www.imdb.com/title/tt0091369/",
        poster: "https://m.media-amazon.com/images/M/MV5BODA2NzQwZmMtYzk4OC00NmQ0LTg2NDAtMmQ0MTc4Nzg1N2VjXkEyXkFqcGc@._V1_.jpg",
    },
    {
        titulo: "Tubarão",
        ano: 1975,
        genero: "Suspense/Terror",
        descricao: "Um tubarão assassino aterroriza uma pequena cidade costeira, levando o chefe da polícia, um biólogo marinho e um caçador de tubarões a tentar capturá-lo.",
        diretor: "Steven Spielberg",
        elenco: "Roy Scheider, Robert Shaw, Richard Dreyfuss",
        link: "https://www.imdb.com/title/tt0073195/",
        poster: "https://m.media-amazon.com/images/M/MV5BYjViNDQzNmUtYzkxZi00NTk5LTljMmItYjJlZmZkODIxNjU1XkEyXkFqcGc@._V1_.jpg",
    }
];